name: Data Platform CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  # Job for Unit and Integration Tests
  test-and-build:
    name: Run Tests & Build Check
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout your code on the GitHub server
      - name: Checkout code
        uses: actions/checkout@v4

      # Step: Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Step: Install 'uv' (ultrafast with cache enabled)
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # Step: Install exact dependencies for your project
      - name: Install dependencies
        run: uv sync --dev

      # Step: Run your Pytest suite
      - name: Run Pytest
        env:
          PYTHONPATH: .
          DB_USER: dummy_user
          DB_PASSWORD: dummy_password
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: dummy_db
          AWS_ACCESS_KEY_ID: dummy_key
          AWS_SECRET_ACCESS_KEY: dummy_secret
          AWS_REGION: us-east-1
          AWS_S3_BUCKET_NAME: dummy-bucket
        run: uv run pytest -v tests/ -W ignore

      # Step: Validate that the Dockerfile builds correctly
      - name: Test Docker Build
        run: docker build -t test-build:latest .
